### ISSUE TITLE
broken in open JDK8

### ISSUE THREAD

**Issue by cloudeng** [vladimirvivien/jmx-cli#4]
A command-line tool for JMX
Powered by Clamshell-Cli framework
http://code.google.com/p/clamshell-cli/

**Java version: 1.8.0_77**
OS: Linux, Version: 3.10.0-229.14.1.el7.x86_64
jmx-cli > ps
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: sun/jvmstat/monitor/HostIdentifier
        at org.clamshellcli.jmx.Management.getHostIdentifier(Management.java:83)
        at org.clamshellcli.jmx.Management.mapVmInfo(Management.java:113)
        at org.clamshellcli.jmx.PsCommand.execute(PsCommand.java:88)
        at org.clamshellcli.jmx.JmxController.handle(JmxController.java:81)
        at org.clamshellcli.impl.CliConsole$1.run(CliConsole.java:150)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: sun.jvmstat.monitor.HostIdentifier
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more

**Comment by cloudeng** [comment]
fixed by copying tools.jar from the JDK's lib directory into the lib directory of jmx-cli
